["v"]
type = "git-repo"
url = "https://github.com/vlang/v.git"
clone.args = ["--depth", "1"]

["roc"]
type = "archive"
url = "https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-macos_apple_silicon-latest.tar.gz"
stripComponents = 1
refreshPeriod = "6h"
